### ISSUE TITLE
구글 로그인 또또또또또또 이슈

### ISSUE THREAD

**Issue by oro7l** [TEAM2-FORCE/force_be#83]
`Access to XMLHttpRequest at 'https://vebeserver.o-r.kr/accounts/google/callback/' from origin 'https://vebe.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`

![image](https://github.com/TEAM2-FORCE/force_be/assets/127576762/ec7e9942-0e99-4d07-9426-db59bba75ceb)

배포 서버에 구글 로그인 시도 시 위와 같은 에러가 뜹니다. 검색 n시간 째 줄 수 있는 설정은 다 줘본 거 같은데 안되네요 (심한욕)

**Comment by devrokket** [comment]
우리 모두 하나가 되어 해결
